# Generated by Django 2.2.1 on 2019-09-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicenow', '0002_auto_20190902_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='serverity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
