# Generated by Django 2.2.1 on 2019-09-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicenow', '0003_auto_20190903_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='updatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='eta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
