# Generated by Django 2.2.1 on 2019-09-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicenow', '0004_auto_20190903_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='inc_dup_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
